services:
  letwinventory-backend:
    image: akl47/letwinventory:latest
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    container_name: letwinventory-backend-prod
    restart: unless-stopped
#   letwinventory-pgadmin:
#     container_name: letwinventory-pgadmin4
#     image: dpage/pgadmin4
#     restart: always
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: root
#     ports:
#       - ${PGADMIN_PORT}:80
#     volumes:
#       - pgadmin_data:/var/lib/pgadmin

# volumes:
#   pgadmin_data:
#     driver: local